---
title: Bought It For Life
email: your-email@domain.com
description: 'Awesome site description here

'
logo: "/assets/images/logo.jpg"
baseurl: ''
url: http://www.boughtitforlife.com
paginate: 5
name: Bought It For Life
bio: 'Mea suas vituperatoribus et, virtute corpora quaestio cum ut. Ne solet nostrum
  complectitur pri, vis ut inani populo.

'
author_image: "/assets/images/author.jpg"
twitter_username: boughtitforlife
analytics_id: UA-91310064-1
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
- jekyll-paginate
- jekyll-seo-tag
